### ISSUE TITLE
Performances : if having 50 subviews or 50 images

### ISSUE THREAD

**Issue by steve21124** [Dromaguirre/DRDynamicSlideShow#2]
From setupSlideShowSubviewsAndAnimations in example, it will add all of them under one view. Will it perform well? or  50 images as slideshow..

or basically how to reuse existing subview with different images and different animation transform

**Comment by Dromaguirre** [comment]
Hi there.

I'm almost ready to release something new that will solve the problem. Long story short, I've decoupled the keyframing/interpolation logic and the scroll view logic into two different projects. Please [__check out__](https://github.com/Dromaguirre/DRDynamicSlideShow/issues/9#issuecomment-81181453) this in order to know all about it.
